# Generated by Django 4.2.7 on 2024-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='use_tls',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
