# Generated by Django 4.2.7 on 2024-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0002_emailconfig_use_tls'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='smtp_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=150),
        ),
    ]
