# Generated by Django 5.0.1 on 2024-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0006_alter_websiteprofiledata_company_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteprofiledata',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
