# Generated by Django 5.0.1 on 2024-01-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0007_websiteprofiledata_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteprofiledata',
            name='company_phone_number3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
