# Generated by Django 5.0.1 on 2024-01-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0009_alter_websiteprofiledata_company_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteprofiledata',
            options={},
        ),
    ]
