# Generated by Django 5.0.1 on 2024-01-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0010_alter_websiteprofiledata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteprofiledata',
            options={'verbose_name_plural': 'Website Profile Data'},
        ),
        migrations.RemoveField(
            model_name='websiteprofiledata',
            name='company_phone_number3',
        ),
        migrations.RemoveField(
            model_name='websiteprofiledata',
            name='zip_code',
        ),
    ]
