# Generated by Django 5.0.1 on 2024-01-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0011_alter_websiteprofiledata_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteProfileData',
        ),
    ]
