# Generated by Django 5.0.1 on 2024-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0014_delete_websiteprofiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phone_number', models.CharField(max_length=50)),
                ('company_phone_number2', models.CharField(blank=True, max_length=50, null=True)),
                ('company_phone_number3', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email_id', models.CharField(max_length=50)),
                ('company_address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address_line_3', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Website Profile Data',
            },
        ),
    ]
