# Generated by Django 5.0.1 on 2024-01-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0015_websiteprofiledata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteProfileData',
        ),
    ]
