# Generated by Django 5.0.1 on 2024-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0020_delete_websiteprofiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phone_number', models.CharField(max_length=50)),
                ('company_email_id', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Website Profile Data',
            },
        ),
    ]
