# Generated by Django 5.0.1 on 2024-01-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0021_websiteprofiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteprofiledata',
            name='company_phone_number2',
            field=models.CharField(default='5592503114', max_length=50),
            preserve_default=False,
        ),
    ]
