# Generated by Django 5.0.1 on 2024-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileManager', '0022_websiteprofiledata_company_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteprofiledata',
            name='company_phone_number3',
            field=models.CharField(default='5596918585', max_length=50),
            preserve_default=False,
        ),
    ]
