# Generated by Django 4.2.7 on 2023-12-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('day_phone', models.CharField(max_length=50)),
                ('night_phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Contact Data',
            },
        ),
    ]
