# Generated by Django 4.2.7 on 2023-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_truckform'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckform',
            name='dot',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
