# Generated by Django 4.2.7 on 2023-12-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_truckform_dot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckform',
            old_name='name',
            new_name='client_name',
        ),
    ]
