# Generated by Django 4.2.7 on 2023-12-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_truckform_msg_truckform_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('dot', models.CharField(max_length=50)),
                ('day_phone', models.CharField(max_length=50)),
                ('night_phone', models.CharField(max_length=50)),
                ('vechile_number', models.CharField(max_length=50)),
                ('text_permit', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': ' Truck Insurance Form Data',
            },
        ),
        migrations.DeleteModel(
            name='TruckForm',
        ),
    ]
