# Generated by Django 4.2.7 on 2023-12-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_truckformdata_delete_truckform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckformdata',
            old_name='vechile_number',
            new_name='vehicle_number',
        ),
        migrations.AddField(
            model_name='truckformdata',
            name='insurance_covered',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
