# Generated by Django 4.2.7 on 2023-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_text_permit_truckformdata_send_text_on_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInsuranceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('dot', models.CharField(max_length=50)),
                ('mc', models.CharField(max_length=50)),
                ('vmodel', models.CharField(max_length=50)),
                ('vnumber', models.CharField(max_length=50)),
                ('vvalue', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': ' Home Insurance Form Data',
            },
        ),
    ]
