# Generated by Django 4.2.7 on 2023-12-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homeinsuranceform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='cname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='vmodel',
            new_name='vehicle_model',
        ),
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='vnumber',
            new_name='vehicle_number',
        ),
        migrations.RenameField(
            model_name='homeinsuranceform',
            old_name='vvalue',
            new_name='vehicle_value',
        ),
    ]
