# Generated by Django 4.2.7 on 2023-12-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_homeinsuranceform_first_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='phone',
        ),
    ]
