# Generated by Django 4.2.7 on 2023-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_homeinsuranceform_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinsuranceform',
            name='client_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
