# Generated by Django 4.2.7 on 2023-12-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_homeinsuranceform_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='client_name',
        ),
    ]
