# Generated by Django 4.2.7 on 2023-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_truckformdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckformdata',
            options={'verbose_name_plural': ' Truck Insurance Form Data'},
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='vehicle_value',
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='full_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='home_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='house_area',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='house_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='pin_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='policy_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
