# Generated by Django 4.2.7 on 2023-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_truckformdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='full_name',
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeinsuranceform',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
