# Generated by Django 4.2.7 on 2024-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_homeinsuranceform_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInsuranceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': ' Life Insurance Form Data',
            },
        ),
        migrations.AlterModelOptions(
            name='truckformdata',
            options={'verbose_name_plural': ' Auto Insurance Form Data'},
        ),
    ]
