# Generated by Django 4.2.7 on 2024-01-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_lifeinsuranceform_alter_truckformdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeinsuranceform',
            name='address',
        ),
        migrations.AddField(
            model_name='lifeinsuranceform',
            name='details',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
