# Generated by Django 4.2.7 on 2024-01-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_lifeinsuranceform_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinsuranceform',
            name='company',
        ),
    ]
