# Generated by Django 4.2.7 on 2024-01-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_homeinsuranceform_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruckFormData',
            new_name='AutoFormData',
        ),
    ]
