# Generated by Django 4.2.7 on 2024-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_truckformdata_autoformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoformdata',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autoformdata',
            name='dot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autoformdata',
            name='mc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinsuranceform',
            name='house_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinsuranceform',
            name='house_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinsuranceform',
            name='pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeinsuranceform',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceform',
            name='details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
