# Generated by Django 5.0.1 on 2024-01-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_autoformdata_company_alter_autoformdata_dot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoFormData',
            new_name='NCAutoFormData',
        ),
    ]
