# Generated by Django 5.0.1 on 2024-01-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_autoformdata_ncautoformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAutoInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('mc', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(max_length=50)),
                ('license_no', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Commercial Auto Insurance Data',
            },
        ),
        migrations.AlterModelOptions(
            name='homeinsuranceform',
            options={'verbose_name_plural': ' Home Insurance Data'},
        ),
        migrations.AlterModelOptions(
            name='lifeinsuranceform',
            options={'verbose_name_plural': ' Life Insurance Data'},
        ),
        migrations.AlterModelOptions(
            name='ncautoformdata',
            options={'verbose_name_plural': 'Non Commercial Auto Insurance Data'},
        ),
        migrations.RemoveField(
            model_name='ncautoformdata',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='ncautoformdata',
            name='mc',
        ),
    ]
